name: 'ad-ws-scan-universal'
author: 'Alexandru Dracea'
description: 'Run a scan using the Whitesource unified agent with java,npm and python language support.'
inputs:
  wssUrl:
    description: 'The relevent URL to your orgs WS Server. Can be found under the Integrate tab of your Whitesource dashboard (e.g. https://app-eu.whitesourcesoftware.com/agent).'
    required: true
  apiKey:
    description: 'API key from Whitesource.'
    required: true
  productName:
    description: 'Name of the Product that this project falls under.'
    required: false
  projectName:
    description: 'Name of the Project. Repository name if not set. Default: Repository Name without owner.'
    required: false
  agentConfig:
    description: 'Filename of whitesource agent configuration if being used (including file path)'
    required: false
  path:
    description: 'Location of the application to be scanned'
    required: false
    default: .
  preRunFile:
    description: 'Filename of a file/script to run before the scan begins.'
    required: false
  failOnPolicyViolations:
    description: '(true/false) Enables Policy violation checks. Still updates inventory and will fail the build when a policy violation is found.'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'silent0ne/universalwss:v0.1.0-20220803.18'
branding:
  icon: 'circle'
  color: 'green'
