name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $(secrets.dhuname)/universalwss:$(date +%s)
    - name: Docker Login
      run: docker login -u $(secrets.dhuname) -p $(secrets.dhtoken)
    - name: Docker Push
      run: docker push $(secrets.dhuname)/universalwss:v0.1.0-$(date +%s)
